### ISSUE TITLE
Disqus Comment System

### ISSUE THREAD

**Issue by abusayed0206** [simarmannsingh/gatsby-netlifycms-modern-blog#2]
## Feature request

**What is the expected behavior?**
I want disqus comment on this template! Ut also has reaction button feature. 

**What is motivation or use case for adding/changing the behavior?**
It already added on todo list.

**How should this be implemented in your opinion?**
Add disqus code on gatsby-config.js and redeploy

**Are you willing to work on this yourself?**
yes

**Comment by simarmannsingh** [comment]
Disqus Comment Functionality added.
